[package]
name = "aws-nuke-lambda"
version = "0.1.0"
authors = ["Ashrith Mekala <ashrith@me.com>"]
edition = "2018"

[dependencies]
aws_nuke = { git = "https://github.com/ashrithr/aws-nuke" }
lambda_runtime = "0.2"
serde_json = "1.0"